spring.application.name=nexo-core

# Configurações do Banco de Dados (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/nexo_db
spring.datasource.username=nexo_user
spring.datasource.password=nexo_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger/OpenAPI (Para você ver suas rotas depois)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html